### ISSUE TITLE
Unable To Deploy App

### ISSUE THREAD

**Issue by Rajeshsahoo12** [developeranaz/URL-Magnet-Cloud-Uploader-Heroku#18]
Have followed all the mentioned as per readme. But got this error at the time of deployment of app. 

Tried changing region too. Used both regions US / EUROPE. But error was same.

Here have attached the error copy too.

Thank
![HEROKU APP DEPLOY ERROR](https://user-images.githubusercontent.com/54216637/148429581-f7c9679e-8c98-432d-8027-8ea0448fd12a.jpg)
s

**Comment by developeranaz** [comment]
[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/843DCF1D5BC45F4572F151A9FC1516437A042A7CC6F979F8B1F1F164AB691D07)

Try deploy using the above Button, above button is working

**Comment by developeranaz** [comment]
1. Fork this repository
2. edit readme.md 
3. replace all `[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/developeranaz/Aria2-Rclone-Remote-Uploader-HEROKU)` to `[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/yourgithubname/Aria2-Rclone-Remote-Uploader-HEROKU)`

**Comment by developeranaz** [comment]
just replace my github name to yours

**Comment by Rajeshsahoo12** [comment]
Let me try both of your steps.

Thanks

**Comment by Rajeshsahoo12** [comment]
Tried now & got this error at heroku.


Thanks

![PRIVATE REPO](https://user-images.githubusercontent.com/54216637/148433431-c9f2a267-bdf8-48ee-be11-fb0322bd91de.jpg)

**Comment by developeranaz** [comment]
did you fork it

**Comment by Rajeshsahoo12** [comment]
Yup I forked it. Then edited my github account name too. Then saved the changes to readme file.

**Comment by Rajeshsahoo12** [comment]
> sorry its my mistake

Okay.

**Comment by developeranaz** [comment]
1. Fork this repository
2. edit readme.md 
3. replace all `[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/developeranaz/Aria2-Rclone-Remote-Uploader-HEROKU)` to `[![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/yourgithubname/URL-Magnet-Cloud-Uploader-Heroku)`

**Comment by developeranaz** [comment]
i did fixed that in my repository
deploy this button 

 [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?template=https://github.com/dev-extended/developeranaz-8111E3FF5D6C27E388B5F85C06A457D92446B3EE940651367466A96CDC24CB6C)`

**Comment by Rajeshsahoo12** [comment]
Thanks @developeranaz for your time & dedication to this tool. It works downloading from magnet & uploading to cloud.

![HEROKU APP WORKING FINE](https://user-images.githubusercontent.com/54216637/148436191-d346a4e3-0381-4007-8bba-4f380affda3e.jpg)

**Comment by developeranaz** [comment]
yeh i did fixed magnet upload recently

**Comment by Rajeshsahoo12** [comment]
I noticed that upload status reporting have some issue. As my magnet contents were of 700 MB of each episodes.

But while upload transfers it was showing in for "GiBytes".

Uploaded GiBytes / Total GiBytes.

And complete I thought of giving logs but they are not there after complete.

**Comment by developeranaz** [comment]
> I noticed that upload status reporting have some issue. As my magnet contents were of 700 MB of each episodes.
> 
> But while upload transfers it was showing in for "GiBytes".
> 
> Uploaded GiBytes / Total GiBytes.
> 
> And complete I thought of giving logs but they are not there after complete.

i tried fixing but failed 
maybe in future i'll learn how to do that

**Comment by Rajeshsahoo12** [comment]
> I noticed that upload status reporting have some issue. As my magnet contents were of 700 MB of each episodes.
> 
> But while upload transfers it was showing in for "GiBytes".
> 
> Uploaded GiBytes / Total GiBytes.
> 
> And complete I thought of giving logs but they are not there after complete.

Just to give info I have tried uploading one more magnet file content to cloud storage. Here is the log of what I told.


Log :-

Your File is downloading.. 
Don't close this tab
[#d89b8d 1.0GiB/1.2GiB(84%) CN:22 SD:2 DL:19MiB ETA:10s]
[#d89b8d 1.1GiB/1.2GiB(97%) CN:14 SD:1 DL:19MiB ETA:1s]
Download Complete
Uploading Started
0 / 0 Bytes, -, 0 Bytes/s, ETA -0 / 0 Bytes, -, 0 Bytes/s, ETA -0 / 4.682 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/9)0 / 4.682 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/9)0 / 4.682 GBytes, 0%, 0 Bytes/s, ETA - (xfr#0/9)6.168M / 4.682 GBytes



Thanks

**Comment by Rajeshsahoo12** [comment]
> 

I use rclone copyurl 'mydownloadlink' onedrive: -a --progress on linux server hosted on vm instance on oracle cloud.

It gives very neat live transfer status.

Let me just update it.

**Comment by Rajeshsahoo12** [comment]
ubuntu@ubuntu:~$ rclone copyurl 'https://indexfiles.reddyharshhaa4.workers.dev/0:/www.1TamilMV.pro%20-%20MAANAADU%20%282021%29%20Tamil%20HDRip%20-%201080p%20-%20HEVC%20-%20AAC%20-%201.5GB%20-%20HC-ESub.mkv' onedrive: -a --progress
Transferred:       54.629 MiB / 1.503 GiB, 4%, 7.143 MiB/s, ETA 3m27s
Transferred:            0 / 1, 0%
Elapsed time:        13.5s
Transferring:
 * www.1TamilMV.pro - MAA… - 1.5GB - HC-ESub.mkv:  3% /1.503Gi, 7.143Mi/s, 3m27s



Thanks

**Comment by Rajeshsahoo12** [comment]
I have uploaded 1st magnet content, after successfull upload to cloud storage. Have reloaded the web page. 

Then provided with 2nd magnet content, and after process got finished show this message.

Noticed that 1st magnet was uploaded ssecond time too. Coz there is 2 time appearing 1st magnet content on cloud.




www.TamilBlasters.sbs - Yakshee (2022) [1080p HQ HD HEVCRip - x265 - [Tamil (Original Video) + Telugu] - AAC - 1.3GB - ESub].mkv - 2nd magnet
www.Tamilblasters.sbs - Cubicles (2021) S02 E01-05 [1080p HD AVC - x264 - UNTOUCHED - [Tam + Tel + Hin + Mal + Kan] - AAC - 3.4GB - ESubs] -1st magnet
Your file uploaded to onedrive at 12 x threads
Refresh this page for New Upload

**Comment by developeranaz** [comment]
ok i know that but 
ithink using download manager is better, cloudflare index are fast but in case of a slow speed direct links threads are important and has mirror download from multiple sources parallel download etc..

**Comment by developeranaz** [comment]
> I have uploaded 1st magnet content, after successfull upload to cloud storage. Have reloaded the web page.
> 
> Then provided with 2nd magnet content, and after process got finished show this message.
> 
> Noticed that 1st magnet was uploaded ssecond time too. Coz there is 2 time appearing 1st magnet content on cloud.
> 
> [www.TamilBlasters.sbs](http://www.TamilBlasters.sbs) - Yakshee (2022) [1080p HQ HD HEVCRip - x265 - [Tamil (Original Video) + Telugu] - AAC - 1.3GB - ESub].mkv - 2nd magnet [www.Tamilblasters.sbs](http://www.Tamilblasters.sbs) - Cubicles (2021) S02 E01-05 [1080p HD AVC - x264 - UNTOUCHED - [Tam + Tel + Hin + Mal + Kan] - AAC - 3.4GB - ESubs] -1st magnet Your file uploaded to onedrive at 12 x threads Refresh this page for New Upload

there are a lot of weard defect in my webapp, and i don't know exactly how how to fix them☹️. 
Each time when i fix an issue newer bugs are appeard ☹️

**Comment by Rajeshsahoo12** [comment]
> > I have uploaded 1st magnet content, after successfull upload to cloud storage. Have reloaded the web page.
> > Then provided with 2nd magnet content, and after process got finished show this message.
> > Noticed that 1st magnet was uploaded ssecond time too. Coz there is 2 time appearing 1st magnet content on cloud.
> > [www.TamilBlasters.sbs](http://www.TamilBlasters.sbs) - Yakshee (2022) [1080p HQ HD HEVCRip - x265 - [Tamil (Original Video) + Telugu] - AAC - 1.3GB - ESub].mkv - 2nd magnet [www.Tamilblasters.sbs](http://www.Tamilblasters.sbs) - Cubicles (2021) S02 E01-05 [1080p HD AVC - x264 - UNTOUCHED - [Tam + Tel + Hin + Mal + Kan] - AAC - 3.4GB - ESubs] -1st magnet Your file uploaded to onedrive at 12 x threads Refresh this page for New Upload
> 
> there are a lot of weard defect in my webapp, and i don't know exactly how how to fix them☹️. Each time when i fix an issue newer bugs are appeard ☹️

@developeranaz I think that how's life & human learns many things in that way only.

Nothing is perfect when it gets started. Things evolve with time & efforts. Only thing we have to try.

This is I do on my linux media server. I think it is part of rclone is doing.

![image](https://user-images.githubusercontent.com/54216637/148442346-1f1c4b4f-f93f-4f4c-addb-d795e74c515d.png)

**Comment by Rajeshsahoo12** [comment]
As all of my queries & doubt were addressed. So, I am closing this issue.

Thanks @developeranaz
